-- ============================================================
--  DAILY TASK MENU -> Supabase
--  Paste ke: Supabase Dashboard > SQL Editor > New query > Run
-- ============================================================

-- 1) Buat tabel menu daily task
create table if not exists public.daily_tasks (
  id bigint generated by default as identity primary key,
  title text not null,        -- label menu: "HARI", "MINGGU", "BULAN"
  slug text,                  -- nama folder foto di daily-task-photos
  period text,                -- periode
  icon text,                  -- emoji fallback
  cls text,                   -- kelas gradient (g-a .. g-h)
  href text,                  -- link halaman (relatif ke modul/)
  description text,           -- deskripsi opsional
  created_at timestamptz not null default now()
);

-- 2) Unik per slug (biar bisa on-conflict / tidak double)
create unique index if not exists daily_tasks_slug_idx on public.daily_tasks (slug) where slug is not null;

-- 3) Isi menu default
insert into public.daily_tasks (title, slug, period, icon, cls, href, description)
values
  ('HARI',   'hari',   'hari',   '☀️', 'g-a', '../utility/hari.html',   'Checklist harian'),
  ('MINGGU', 'minggu', 'minggu', '📅', 'g-b', '../utility/minggu.html', 'Checklist mingguan'),
  ('BULAN',  'bulan',  'bulan',  '🌙', 'g-c', '../utility/bulan.html',  'Checklist bulanan')
on conflict (slug) do nothing;

-- 4) Aktifkan Row Level Security + izinkan akses dari app (anon key)
alter table public.daily_tasks enable row level security;

drop policy if exists "daily_tasks public read"   on public.daily_tasks;
drop policy if exists "daily_tasks public insert" on public.daily_tasks;
drop policy if exists "daily_tasks public update" on public.daily_tasks;
drop policy if exists "daily_tasks public delete" on public.daily_tasks;

create policy "daily_tasks public read"   on public.daily_tasks for select using (true);
create policy "daily_tasks public insert" on public.daily_tasks for insert with check (true);
create policy "daily_tasks public update" on public.daily_tasks for update using (true);
create policy "daily_tasks public delete" on public.daily_tasks for delete using (true);